# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku
#
# Shared Kconfig for handwire36 (both halves)

# Enable ZMK split keyboard support
CONFIG_ZMK_SPLIT=y

# Enable BLE split (nice!nano)
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_BT=y

# Optional: enable USB for the central half (left)
# CONFIG_ZMK_USB=y
