# Copyright 2024 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build handwire36'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["handwire36_left","handwire36_right"]'
